apiVersion: apps/v1
kind: Deployment
metadata:
  # Change example to a name identifying the gateway
  name: geneos-gateway-example
spec:
  selector:
    matchLabels:
      # Change example to a name identifying the gateway
      app: geneos-gateway-example
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Change example to a name identifying the gateway
        app: geneos-gateway-example
    spec:
      imagePullSecrets:
          # Name of the secret that contains the authentication key for
          # docker.itrsgroup.com
        - name: regcred
      securityContext:
        runAsUser: 100
        fsGroup: 101
      containers:
        - name: gateway
          # Update the image to match the gateway you wish to use
          image: docker.itrsgroup.com/gateway:5.4.0-SNAPSHOT-b9195ee84
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /gateway/config
              readOnly: true
          ports:
            - containerPort: 7039
      volumes:
        - name: config
          configMap:
            # Change example to a name identifying the gateway
            name: geneos-gateway-example-config
            items:
              - key: gci
                path: gateway.gci
        - name: persist
          persistentVolumeClaim:
            # Change example to a name identifying the gateway
            claimName: geneos-gateway-example-pvc
          # Add Certificate secret here if needed     