apiVersion: apps/v1
kind: Deployment
metadata:
  name: geneos-example-gateway
spec:
  selector:
    matchLabels:
      app: geneos-gateway
      id: DemoGateway
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geneos-gateway
        id: DemoGateway
    spec:
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsUser: 100
        fsGroup: 101
      containers:
        - name: gateway
          image: docker.itrsgroup.com/geneos-gateway:5.4.0-SNAPSHOT-a027729d2
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /gateway/config
              readOnly: true
          ports:
            - containerPort: 7039
      imagePullSecrets:
        - name: docker.itrsgroup.com.cred
      volumes:
        - name: config
          configMap:
            name: geneos-example-gateway-config
            items:
              - key: gci
                path: gateway.gci
                