apiVersion: v1
kind: Service
metadata:
  name: geneos-example-gateway-external
spec:
  type: LoadBalancer
  selector:
    app: geneos-gateway
    id: DemoGateway
  ports:
    - port: 7039
      targetPort: 7039