apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Change example to a name identifying the gateway
  name: geneos-gateway-example-pvc
spec:
  # If you are using a StorageClass to build the PersistentVolume that matches this PersistentVolumeClaim
  # then uncomment the line below and set the correct storageClassName name for your cluster
  #storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
